import numpy as np 
import matplotlib.pyplot as plt 
import csv

def converge(file):
    file_to_read = open(file, 'r')
    csvreader = csv.reader(file_to_read)
    info_to_plot = []
    for row in csvreader: 
        current_row = [float(row[0]), float(row[1]), float(row[2])]
        info_to_plot.append(current_row)
    # info_to_plot = np.array(info_to_plot)
    file_to_read.close()
    return np.array(info_to_plot)

# K_final = converge('convergence?/K_final.csv')
# plt.loglog(K_final[:, 0], K_final[:, 1], label='K_final_analytical')
# plt.loglog(K_final[:, 0], K_final[:, 2], label='K_final_numerical')
# plt.title('log-log plot of K_final .vs. number of blades')
# plt.xlabel('number of blades []')
# plt.ylabel('K_final []')
# plt.legend()
# plt.show()

# x0_0 = converge('convergence?/x0_0.csv')
# plt.loglog(x0_0[:, 0], x0_0[:, 1], label='x0_0_analytical')
# plt.loglog(x0_0[:, 0], x0_0[:, 2], label='x0_0_numerical')
# plt.title('log-log plot of x0_0 .vs. number of blades')
# plt.xlabel('number of blades []')
# plt.ylabel('x0_0 []')
# plt.legend()
# plt.show()

# x0_1 = converge('convergence?/x0_1.csv')
# plt.loglog(np.abs(x0_1[:, 0]), np.abs(x0_1[:, 1]), label='x0_1_analytical')
# plt.loglog(np.abs(x0_1[:, 0]), np.abs(x0_1[:, 2]), label='x0_1_numerical')
# plt.title('log-log plot of x0_1 .vs. number of blades')
# plt.xlabel('number of blades []')
# plt.ylabel('x0_1 []')
# plt.legend()
# plt.show()

# x0_2 = converge('convergence?/x0_2.csv')
# plt.loglog(x0_2[:, 0], x0_2[:, 1], label='x0_2_analytical')
# plt.loglog(x0_2[:, 0], x0_2[:, 2], label='x0_2_numerical')
# plt.title('log-log plot of x0_2 .vs. number of blades')
# plt.xlabel('number of blades []')
# plt.ylabel('x0_2 []')
# plt.legend()
# plt.show()

# x0_3 = converge('convergence?/x0_3.csv')
# plt.loglog(np.abs(x0_3[:, 0]), np.abs(x0_3[:, 1]), label='x0_3_analytical')
# plt.loglog(np.abs(x0_3[:, 0]), np.abs(x0_3[:, 2]), label='x0_3_numerical')
# plt.title('log-log loglog of x0_3 .vs. number of blades')
# plt.xlabel('number of blades []')
# plt.ylabel('x0_3 []')
# plt.legend()
# plt.show()

K_final = converge('convergence?/K_final_run2.csv')
plt.loglog(K_final[:, 0], K_final[:, 1], label='K_final_analytical')
plt.loglog(K_final[:, 0], K_final[:, 2], label='K_final_numerical')
plt.title('log-log plot of K_final .vs. number of blades')
plt.xlabel('number of blades []')
plt.ylabel('K_final []')
plt.legend()
plt.show()

x0_0 = converge('convergence?/x0_0_run2.csv')
plt.loglog(x0_0[:, 0], x0_0[:, 1], label='x0_0_analytical')
plt.loglog(x0_0[:, 0], x0_0[:, 2], label='x0_0_numerical')
plt.title('log-log plot of x0_0 .vs. number of blades')
plt.xlabel('number of blades []')
plt.ylabel('x0_0 []')
plt.legend()
plt.show()

x0_1 = converge('convergence?/x0_1_run2.csv')
plt.loglog(np.abs(x0_1[:, 0]), np.abs(x0_1[:, 1]), label='x0_1_analytical')
plt.loglog(np.abs(x0_1[:, 0]), np.abs(x0_1[:, 2]), label='x0_1_numerical')
plt.title('log-log plot of x0_1 .vs. number of blades')
plt.xlabel('number of blades []')
plt.ylabel('x0_1 []')
plt.legend()
plt.show()

x0_2 = converge('convergence?/x0_2_run2.csv')
plt.loglog(x0_2[:, 0], x0_2[:, 1], label='x0_2_analytical')
plt.loglog(x0_2[:, 0], x0_2[:, 2], label='x0_2_numerical')
plt.title('log-log plot of x0_2 .vs. number of blades')
plt.xlabel('number of blades []')
plt.ylabel('x0_2 []')
plt.legend()
plt.show()

x0_3  = converge('convergence?/x0_3_run2.csv')
plt.loglog(np.abs(x0_3[:, 0]), np.abs(x0_3[:, 1]), label='x0_3_analytical')
plt.loglog(np.abs(x0_3[:, 0]), np.abs(x0_3[:, 2]), label='x0_3_numerical')
plt.title('log-log loglog of x0_3 .vs. number of blades')
plt.xlabel('number of blades []')
plt.ylabel('x0_3 []')
plt.legend()
plt.show()